### PR TITLE
Fix #14 by adding a `binary` option

### LINKED ISSUE #14: Strange characters aren't transmitted properly
As an example, echoing `’` returns `<<195, 162, 194, 128, 194, 153>>` instead of `’`.

### PR DESCRIPTION
**Pull request by ccapndave**
Added a `binary` option to support receiving unicode characters.

### CODE REVIEW

**Comment by jwietelmann** [comment]
I'm going to merge this, but should we maybe consider a follow-up to set the option default to `true`? Any downsides to that?

**Comment by jwietelmann** [comment]
Coveralls server is acting crazy right now and messing up CI. Will merge when we get CI to run all the way through.

**Comment by anamba** [comment]
Just ran into this one today and was curious about the status of this PR.

**Comment by ccapndave** [comment]
Just to let you know I've been using this branch in production for ages now without any problems so it does seem like it works.

**Comment by oohnoitz** [comment]
I'm just gonna go ahead and merge this in.

**Pull request merged**
