### PR TITLE
Fix NODE_PATH for Node process

### PR DESCRIPTION
**Pull request by sineed**

### CODE REVIEW

**Comment by jwietelmann** [comment]
Sorry, I was wrong! I'm not sure what I thought the code already did, but you definitely found a problem. I'm going to re-open this and try to figure out if this is the right direction to go or not.

**Comment by sineed** [comment]
Hi @jwietelmann Joel! Sorry I forgot to add a description, I just fixed on my side and decided to submit a PR.

I started using the library today and realized that the `path` option is not used when it is specified in `NodeJS.Supervisor.start_link/1` function. I found that when the node process is launched the `NODE_PATH` env variable is [specified](https://github.com/revelrylabs/elixir-nodejs/blob/master/lib/nodejs/worker.ex#L33). But in `server.js` file [there is](https://github.com/revelrylabs/elixir-nodejs/blob/master/priv/server.js#L3) only `MODULE_SEARCH_PATH` invocation from env.

So I decided that there is a mistake for `path` handling: `MODULE_SEARCH_PATH` actualy is `NODE_PATH`. But maybe `MODULE_SEARCH_PATH` has different intention that I don't know

**Comment by jwietelmann** [comment]
@sineed So I think what happened was that I had intended to use `MODULE_SEARCH_PATH` and not `NODE_PATH`. I just forgot to update the Elixir `Port` config. And then I think all my testing and usage worked anyway because when `MODULE_SEARCH_PATH` doesn't exist, this:

```
const path = require('path')
const readline = require('readline')
const { MODULE_SEARCH_PATH } = process.env
const WRITE_CHUNK_SIZE = parseInt(process.env.WRITE_CHUNK_SIZE, 10)

function rewritePath(oldPath) {
  return oldPath
  const [_1, _2, relative, name] = oldPath.match(/^((\.\.?)\/)?(.*)$/)

  if (relative) {
    return path.join(MODULE_SEARCH_PATH, relative, name)
  }

  return path.join(MODULE_SEARCH_PATH, 'node_modules', name)
}

function requireModule(modulePath) {
  const newPath = rewritePath(modulePath)

  // When not running in production mode, refresh the cache on each call.
  if (process.env.NODE_ENV !== 'production') {
    delete require.cache[require.resolve(newPath)]
  }

  return require(newPath)
}
```

...results in _almost_ exactly the same behavior as having set the `NODE_PATH`. My big question right now is which direction to go. I don't love `NODE_PATH` because it makes every module's `require` behave differently than the default. On the other hand, this is (apparently!) what I already used, so it's just a minor version bump.

Okay, let's do this: *Leave your PR as-is, but bump the minor version for me.* I'll merge and publish. And then I'll probably go back and get rid of `NODE_PATH` in favor of `MODULE_SEARCH_PATH` later, which will be a major version release.

**Comment by oohnoitz** [comment]
I'm going to close this as it should be resolved in #30. I'd recommend opening an issue if this is still an issue that needs to be resolved.

**Pull request closed without merging**
